# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06895a1802ab0c4148a07b4e499852db59cb800a4a9b66a65bbb7569cb7c96aefbdfbbe7267854aa9cc1aad37a4dfeddb674ef9a996b816641bf45b913548a13

test:
  secret_key_base: 63c36ab92cac69d8249224381e52169605a6c5c4f4700bbbaeb2be53365c8f53a1942012a0cbdb026e7e812b450e188d4c616e5522c02f7da689d304de5618db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
